---
- include_role:
    name: andrewrothstein.cfssl
- name: creating {{ pki_dir }}
  file:
    path: '{{ pki_dir }}'
    state: directory
    mode: 0700

- name: writing ca-config.json ({{ pki_ca_config_json }})
  template:
    src: ca-config.json.j2
    dest: '{{ pki_ca_config_json }}'
    mode: 0600

- name: writing cacsr.json ({{ pki_cacsr_json }})
  template:
    src: cacsr.json.j2
    dest: '{{ pki_cacsr_json }}'
    mode: 0600

- name: creating csr.json ({{ pki_csr_json }})
  template:
    src: csr.json.j2
    dest: '{{ pki_csr_json }}'
    mode: 0600

- name: creating CA CSR ({{ pki_ca_csr }})
  when: not pki_self_sign
  shell: cfssl genkey cacsr.json | cfssljson -bare ca
  args:
    chdir: '{{ pki_dir }}'
    creates: '{{ pki_ca_csr }}'

- name: create certificate authority key pair and CSR ({{ pki_ca_pem }})
  when: pki_self_sign
  shell: cfssl genkey -initca cacsr.json | cfssljson -bare ca
  args:
    chdir: '{{ pki_dir }}'
    creates: '{{ pki_ca_pem }}'

- name: generating CA pfx ({{ pki_ca_pfx }})
  when: pki_self_sign
  shell: >-
    openssl pkcs12
    -inkey ca-key.pem
    -in ca.pem
    -export
    -out ca.pfx
    -passout pass:
  args:
    chdir: '{{ pki_dir }}'
    creates: '{{ pki_ca_pfx }}'

- name: generating client csr.json files
  with_items: '{{ pki_servers }}'
  template:
    src: csr.json.j2
    dest: '{{ pki_dir }}/{{ item.cname }}.json'

- name: generating keys/certs
  with_items: '{{ pki_servers }}'
  shell: >-
    cfssl gencert
    -ca={{ pki_ca_pem }}
    -ca-key={{ pki_dir }}/ca-key.pem
    -config={{ pki_dir }}/ca-config.json
    {% if 'profile' in item %}-profile={{ item.profile }}{% endif %}
    {{ item.cname }}.json
    | cfssljson -bare {{ item.cname }}
  args:
    chdir: '{{ pki_dir }}'
    creates: '{{ pki_dir }}/{{ item.cname }}.pem'

- name: generating PFX...
  with_items: '{{ pki_servers }}'
  shell: >-
    openssl pkcs12
    -inkey {{ item.cname }}-key.pem
    -in {{ item.cname }}.pem
    -export
    -out {{ item.cname }}.pfx
    -passout pass:
  args:
    chdir: '{{ pki_dir }}'
    creates: '{{ pki_dir }}/{{ item.cname }}.pfx'
